apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris
  namespace: tetris
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tetris
  project: sandbox
  source:
  repoURL: 'https://github.com/SkylarHoughtonGithub/shoutsky-containers.git'
  path: kubernetes/manifests/applications/tetris
  targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
