version: “3.3”

services:
  dns:
    image: coredns/coredns
    container_name: coredns
    ports:
    - 53:53
    volumes:
    - ./CoreDNS/config/Corefile:/root/Corefile
    networks:
      network:
        ipv4_address: 10.5.0.2

  vault:
    build:
      context: .
      dockerfile: ./HashiVault/Dockerfile
    container_name: vault
    environment:
    - VAULT_ADDR=http://127.0.0.1:8200
    - VAULT_API_ADDR=http://127.0.0.1:8200
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    networks:
      network:
        ipv4_address: 10.5.0.5

  prom:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - ./Prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      network:
        ipv4_address: 10.5.0.6

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
    - 9100:9100
    networks:
      network:
        ipv4_address: 10.5.0.7

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
