apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "tetris-react-app.fullname" . }}
  namespace: {{ .Values.argoCD.namespace }}
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Release.Namespace }}
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-tetris-react-repo.git'
    path: 'path/to/tetris-react-app'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
