# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tetris-react-app.fullname" . }}
  labels:
    app: {{ include "tetris-react-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tetris-react-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tetris-react-app.name" . }}
    spec:
      containers:
      - name: tetris-react-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
