global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets: ['10.5.0.6:9090']

- job_name: "node"
  scrape_interval: 10s
  static_configs:
  - targets: ["10.5.0.7:9100"]
                                   